services:
  - type: web
    name: telegram-automarkdown-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        fromSecret: BOT_TOKEN
      - key: APP_URL
        value: https://<YOUR_SERVICE_NAME>.onrender.com
